### ISSUE TITLE
CPU or GPU

### ISSUE THREAD

**Issue by XinyeDu1204** [wxjiao/AGHMN#5]
Hi, is the running environment of your code CPU or GPU?

And could you tell me the running order of these files if I want to run your code? 

Thank you very much!

**Comment by wxjiao** [comment]
> Hi, is the running environment of your code CPU or GPU?
> 
> And could you tell me the running order of these files if I want to run your code?
> 
> Thank you very much!

Hi @XinyeDu1204, the code can be run on both cpu and gpu. 
As for the running order of files, it is similar as https://github.com/wxjiao/HiGRUs.
Thanks!

**Comment by XinyeDu1204** [comment]
OK.
Thanks for your reply!!
